name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: echo '${{ secrets.PUBLISH_DOMAIN }}' > ./web/CNAME
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /